export const linkToMint = 'https://www.google.com';

export const phases = {
  phase1: [
    '- Create a collection of 555 okay degens',
    '- Set up discord and twitter',
    '- Give out WL and OG',
    '- Determine a mint date',
    '- END OF MINT',
  ],
  phase2: [
    '- Get lissted on  ME',
    '- Set up Holder Verification',
    '- Add 500 SOL into LP for staking token $OKDEGEN',
    '- Come out with Staking System',
    '- Raffle NFTs ussing token $OKDEGEN',
  ],
  phase3: [
    '- Release our own launchpad and doxing service to ensure a rug free ecosystem.',
    '- Open up applications for projects to be on our launchpad.',
    '- Holders will receive 50% of revenue made from launchpad (We will take 6% of the mint monney of the projects which will launch on the Okaypad).',
    '- Only staked Okaydegen NFTs receive revenue.',
  ],
  phase4: [
    '- Send your Okaydegen on a mission to find a pack and go hunt for $OKDEGEN, the hunt last 20 days and you will receive 1.7x more $OKDEGEN (Price to set your Okaydegen on a mission will be revealed once token is made).',
  ],
  phase5: [
    '- There will be 10 1/1 Legendary OkayDegens, these degens will receive 5x $OKDEGEN coin from normal staking, the auctions will be held in SOL (75% of ALL auctions will go to the community wallet, Votes will be held for what the money is used for in the wallet).',
  ],
  phase6: [
    '- Gather enough $OKDEGEN to mint a female Okaydegen, Female okay degens will earn an additional 1.5x $OKDEGEN from the normal staking. (females will not be able to form a pack and hunt).',
    '- Female okay degens will also be listed on ME.',
  ],
};

export const whitepaper = {
  p0: 'Okay Degen is a 555-degen collection created on the Solana blockchain. We are creating a project in which our holders interact with their NFTs in a number of ways while also benefiting from the various utilities that we will release as soon as we become a DAO. We will lay down each phase of our roadmap in this Whitepaper so that you may better grasp our vision.',
  p1: [
    'This is where the Okay Degen team comes in to produce a project unlike any other in the Solana ecosystem. We begin by building our social media accounts and growing them as naturally as possible',
    'Throughout this time, we will establishing a strong community in our discord. We will announce a mint date whenever we are confident in our progress.',
  ],
  p2: [
    'This is what we refer to as the degens hunting season. Our collection will be placed on MagicEden as soon as it sells out, and we will introduce holder verification for our discord, allowing holders access to normally blocked channels. As long as their NFT is not offered on any marketplace, every degen holder will receive an updated role. Our DAO is born as a result of this.',
    'The next stage is to create a liquidity pool that will allow our degens to be staked for yield. So thats where we expose you to $OKDEGEN, our native cryptocurrency.',
    ,
    'We will contribute 500 SOL to the liquidity pool as soon as the coin is released. This will add value to $OKDEGEN, your token, which will be required for all transactions in our ecosystem. We also chose to add instant utility to $OKDEGEN for our holders throughout this time. $OKDEGEN will be able to be used to enter a raffle for other NFTS auctions.',
  ],
  p3: [
    'We will be launching our launchpad alongside a thorough vetting service to verify that any project that goes live on our platform is genuine and not a scam.',
    'Our team consists of people who genuinely care about Solana and its NFT environment, thus this service will not be compromised in any way. Every other idea that fills out our application form to debut on our platform will be researched by a specialized staff.',
    'We will charge a fee of 6% of mint money to projects that use our launchpad once they have been approved. Our holders in Sol will receive 50 percent of the revenue generated by our launchpad.',
    'This applies solely to our holders who have staked their degens on our staking platform. Not only will our launchpad be devoid of scams, but it will also offer the best minting service in Solana. We believe this is the appropriate launchpad service for Solana.',
  ],
  p4: [
    'As the saying goes, "if you want to go fast, go alone." Degens are stronger in packs, so we come up with phase 4 of forming a pack.',
    'Our holders will be able to send their degen on a mission to join a pack and hunt for $OKDEGEN. This quest will last 15 days, and each participant will receive 1.7 times more $OKDEGEN. The cost of sending your degen on a mission will be revealed as soon as our token is created.',
  ],
  p5: [
    'There will be a 10 legendary degens collection in addition to the 555 collection. This collection of degens will be absolutely unique, making each one a one-of-a-kind. We will implement a way to auction off our famous degens during this period.',
    'Due to the auctions exclusivity, you will need Sol to participate. The best thing is that we have decided to put 75% of all proceeds from auctions into our community wallet. The DAO will be able to vote on how this money should be used. The options are truly limitless.',
  ],
  p6: [
    'Degens are faithful in the wild, which means they mate for life. Every okay degen holder will be allowed to mint a female degen in phase 6. This mint will be in $OKDEGEN, and more information will be released as soon as possible.',
    'The aim is to amass as much $OKDEGEN as possible in order to mint a female and utilize it for all of our ecosystems other need. When compared to a male degen, staking a female degen will result in a 1.5x increase in yield. It is also worth noting that female degens will not be allowed to hunt or participate in missions because the male is in charge. After the mint, female okay degen will be listed on MagicEden.',
  ],
};
